In [1]:
import numpy as np  #numpy is a library which will be inside lib
a=np.array([1,2,3,45])
a

array([ 1,  2,  3, 45])

In [2]:
type(a)

numpy.ndarray

In [3]:
a.shape  #tuple of array dimensions (rows,columns) if 1 row means 1 dim then only column count will be listed

(4,)

In [4]:
a.ndim #dimension of array

1

In [5]:
b=np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [6]:
b.shape

(2, 3)

In [7]:
b.ndim

2

In [8]:
c=np.array([[4,5,6],[7,8,9]],dtype=float)
c

array([[4., 5., 6.],
       [7., 8., 9.]])

In [9]:
c.reshape(3,2)  #Reshape to change the dimensions

array([[4., 5.],
       [6., 7.],
       [8., 9.]])

In [10]:
d=np.zeros(6)
d

array([0., 0., 0., 0., 0., 0.])

In [11]:
e=np.ones((6,6),dtype=int)
e

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [12]:
lst=([1,2],[3,4],[5,6])
x=np.asarray(lst)
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
y=np.arange(0,16,3)
y

array([ 0,  3,  6,  9, 12, 15])

In [14]:
type(y)


numpy.ndarray

In [15]:
z=np.linspace(10,20,5)  #dividing the scope (end is included) with part value
z

array([10. , 12.5, 15. , 17.5, 20. ])

In [16]:
k=np.array([[1,2,3],[4,5,6],[7,8,9]])
k[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [17]:
k[2,1]

8

In [18]:
k[...,1]

array([2, 5, 8])

In [19]:
k.ndim

2

In [20]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
z=x[1:4,1:3]
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [22]:
z[z>4]

array([ 5,  7,  8, 10, 11])

In [23]:
#model should contain only value if not a value then nan==>not a value
a=np.array([1,5,np.nan,8,np.nan,52,65,np.nan])
a


array([ 1.,  5., nan,  8., nan, 52., 65., nan])

In [24]:
a[~np.isnan(a)]  #compliment means not  (omitting Nan using compliment operator tilde)

array([ 1.,  5.,  8., 52., 65.])

In [25]:
z

array([[ 4,  5],
       [ 7,  8],
       [10, 11]])

In [26]:
import numpy as np
l = np.arange(10)
a1 = slice(2, 9, 2)
print(l[a1])

l1 = np.arange(10)
b1 = l[2: 9: 2]
print(l1[b1])

[2 4 6 8]
[2 4 6 8]


In [65]:
#broadcasting ==>Manipulation of arrays
x=np.array([5,7])
y=np.array([1,2])
z=x*y
print(z)
print(z.shape)
z.ndim

[ 5 14]
(2,)


1

In [28]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x.T


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [29]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
x


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
x.reshape(3,4)
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [32]:
x=np.array([[5,7],[8,9]])
y=np.array([[1,2],[14,15]])    #default axis is 0 (row addition)
b=np.concatenate((x,y))
print(b.shape)
print(b)
b.ndim
b.shape


(4, 2)
[[ 5  7]
 [ 8  9]
 [ 1  2]
 [14 15]]


(4, 2)

In [33]:
a=np.stack((x,y))
print(a.shape)#array of arrays  and dimension changes --> shape won't change
print(a)
a.ndim
a.shape

(2, 2, 2)
[[[ 5  7]
  [ 8  9]]

 [[ 1  2]
  [14 15]]]


(2, 2, 2)

In [34]:
x=np.array([[5,7],[8,9]])
y=np.array([[1,2],[14,15]])    #default axis is 0 (row addition==>column wise) , axis=1 (column addition==>row wise)
np.concatenate((x,y),axis=1)

array([[ 5,  7,  1,  2],
       [ 8,  9, 14, 15]])

In [35]:
np.hstack((x,y))   


array([[ 5,  7,  1,  2],
       [ 8,  9, 14, 15]])

In [36]:
np.vstack((x,y))

array([[ 5,  7],
       [ 8,  9],
       [ 1,  2],
       [14, 15]])

In [37]:
a=np.arange(9)
np.split(a,3)   #splitting into sets pf  3 



[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [38]:
a=np.array([[10,20,30],[40,50,60]])
np.append(a,[[1,2,3]])

array([10, 20, 30, 40, 50, 60,  1,  2,  3])

In [39]:
a=np.array([[10,20,30],[40,50,60]])
np.append(a,[[1,2,3]],axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [ 1,  2,  3]])

In [40]:
a=np.array([[10,20,30],[40,50,60]])
np.append(a,[[1,2,3],[70,80,88]],axis=1)

array([[10, 20, 30,  1,  2,  3],
       [40, 50, 60, 70, 80, 88]])

In [41]:
a=np.array([[1,2],[3,4],[5,6]])
np.insert(a,1,[7,8],axis=0)

array([[1, 2],
       [7, 8],
       [3, 4],
       [5, 6]])

In [42]:
a=np.array([[1,2],[3,4],[5,6]])
np.insert(a,1,[7],axis=1)    #column 1 will take 7 3 times if given 2 values [7,8] error will come

array([[1, 7, 2],
       [3, 7, 4],
       [5, 7, 6]])

In [43]:
a=np.array([[1,2],[3,4],[5,6]])
np.insert(a,1,[7,8,9],axis=1)    #column 1 has the given values

array([[1, 7, 2],
       [3, 8, 4],
       [5, 9, 6]])

In [44]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
np.delete(a,1,axis=0)


array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [46]:
np.delete(a,1,axis=1)

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [47]:
a=np.array([1,3,3,3,4,5])
np.unique(a)

array([1, 3, 4, 5])

In [48]:
x=np.arange(9,dtype=float).reshape(3,3)
print(x)
y=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.add(x,y))

x=np.arange(9,dtype=float).reshape(3,3)
print(x)
y=np.array([1,2,3])
print(np.add(x,y))


[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [13. 15. 17.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 1.  3.  5.]
 [ 4.  6.  8.]
 [ 7.  9. 11.]]


In [49]:
np.subtract(x,y)

array([[-1., -1., -1.],
       [ 2.,  2.,  2.],
       [ 5.,  5.,  5.]])

In [50]:
np.multiply(x,y)

array([[ 0.,  2.,  6.],
       [ 3.,  8., 15.],
       [ 6., 14., 24.]])

In [51]:
np.power(x,2)

array([[ 0.,  1.,  4.],
       [ 9., 16., 25.],
       [36., 49., 64.]])

In [52]:
a=np.array([[30,40,70],[80,20,10],[50,90,60]])
a

array([[30, 40, 70],
       [80, 20, 10],
       [50, 90, 60]])

In [53]:
np.percentile(a,50,axis=1)

array([40., 20., 60.])

In [54]:
np.percentile(a,50,axis=0)

array([50., 40., 60.])

In [55]:
np.percentile(a,100,axis=0)

array([80., 90., 70.])

In [56]:
np.percentile(a,100,axis=1)

array([70., 80., 90.])

In [57]:
print(np.mean(a,axis=0))

[53.33333333 50.         46.66666667]


In [58]:
print(np.mean(a,axis=1))

[46.66666667 36.66666667 66.66666667]


In [59]:
print(np.median(a,axis=0))

[50. 40. 60.]


In [60]:
print(np.median(a,axis=1))

[40. 20. 60.]


In [61]:
print(np.std([5,8,7,20]))

5.873670062235365


In [62]:
print(np.std(a,axis=1))

[16.99673171 30.91206165 16.99673171]


In [63]:
print(np.var([5,8,7,20]))

34.5


In [66]:

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])