In [11]:
#Linear algebra:
import numpy as np
#array=np.matrix('1,2 : 3,4')
X=np.matrix([[3,1,4],[1,5,9],[2,6,5]])
print(X)

[[3 1 4]
 [1 5 9]
 [2 6 5]]


In [12]:
X.I

matrix([[ 0.32222222, -0.21111111,  0.12222222],
        [-0.14444444, -0.07777778,  0.25555556],
        [ 0.04444444,  0.17777778, -0.15555556]])

#### X.T


In [6]:
Y=np.matrix([[1,2] , [3,4]])
print(Y)

[[1 2]
 [3 4]]


In [16]:
a=[1,2,3,4,5]
b=[6,7,8,9,10]
print(a+b)
output=[]
for a,b in zip(a,b):
    output.append(a+b)
print(output)    
    

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[7, 9, 11, 13, 15]


In [18]:
import pandas as pd
arr=[0,1,2,3,4]
s1=pd.Series(arr)
print(s1)


0    0
1    1
2    2
3    3
4    4
dtype: int64


In [19]:
order=[1,2,3,4,5]
s2=pd.Series(arr,index=order)
print(s2)

1    0
2    1
3    2
4    3
5    4
dtype: int64


In [20]:
print(s1)
s1.index=['A','B','C','D','E']
print(s1)

0    0
1    1
2    2
3    3
4    4
dtype: int64
A    0
B    1
C    2
D    3
E    4
dtype: int64


In [21]:
d={'a':1,'b':2}
s3=pd.Series(d)
print(s3)

a    1
b    2
dtype: int64


In [22]:
s4=s1.append(s3)
s4

A    0
B    1
C    2
D    3
E    4
a    1
b    2
dtype: int64

In [28]:
s4.drop('D')
print(s4)


A    0
B    1
C    2
D    3
E    4
a    1
b    2
dtype: int64


In [34]:
print(s1)
print(s4)
s1.add(s4)

A    0
B    1
C    2
D    3
E    4
dtype: int64
A    0
B    1
C    2
D    3
E    4
a    1
b    2
dtype: int64


A    0.0
B    2.0
C    4.0
D    6.0
E    8.0
a    NaN
b    NaN
dtype: float64

In [36]:
print(s1)
print(s3)
s1.add(s3)

A    0
B    1
C    2
D    3
E    4
dtype: int64
a    1
b    2
dtype: int64


A   NaN
B   NaN
C   NaN
D   NaN
E   NaN
a   NaN
b   NaN
dtype: float64

AttributeError: 'list' object has no attribute 'sub'

In [41]:
X=[1,2,3,4,5]
Y=[7,8,9,10,11,12,13]
s5=pd.Series(X)
s6=pd.Series(Y)
s5.add(s6)

0     8.0
1    10.0
2    12.0
3    14.0
4    16.0
5     NaN
6     NaN
dtype: float64

In [42]:
s5.sub(s6)

0   -6.0
1   -6.0
2   -6.0
3   -6.0
4   -6.0
5    NaN
6    NaN
dtype: float64

In [43]:
s5.div(s6)

0    0.142857
1    0.250000
2    0.333333
3    0.400000
4    0.454545
5         NaN
6         NaN
dtype: float64

In [44]:
s5.mul(s6)

0     7.0
1    16.0
2    27.0
3    40.0
4    55.0
5     NaN
6     NaN
dtype: float64

In [45]:
s5.multiply(s6)

0     7.0
1    16.0
2    27.0
3    40.0
4    55.0
5     NaN
6     NaN
dtype: float64

In [46]:
print(s5)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [47]:
s5.drop(4)

0    1
1    2
2    3
3    4
dtype: int64

In [50]:
s5.index=['A','B','C','D','E']
print(s5)

A    1
B    2
C    3
D    4
E    5
dtype: int64


In [51]:
s5=s5.drop('A')

In [52]:
print(s5)

B    2
C    3
D    4
E    5
dtype: int64


In [53]:
order=[1,2,3,4,5]
s5=pd.Series(arr,index=order)
print(s5)

1    0
2    1
3    2
4    3
5    4
dtype: int64


In [54]:
print(s5)

1    0
2    1
3    2
4    3
5    4
dtype: int64


In [55]:
print(s6)

0     7
1     8
2     9
3    10
4    11
5    12
6    13
dtype: int64


In [57]:
order=[1,2,3,4,5]
s6=pd.Series(arr,index=order)
print(s6)

1    0
2    1
3    2
4    3
5    4
dtype: int64


In [58]:
s6.add(s5)

1    0
2    2
3    4
4    6
5    8
dtype: int64

In [59]:
#Create Dataframe #2D array which has rows and columns:
index_dates=pd.date_range('today',periods=6)
column=['A','B','C','D']
num_arr=np.random.randn(6,4)
df1=pd.DataFrame(num_arr,index=index_dates,columns=column)   #index is row title and columns is column title
print(df1)

                                   A         B         C         D
2019-03-16 17:56:14.994758 -0.153244 -2.442910 -0.811786  0.502355
2019-03-17 17:56:14.994758 -0.120559  0.247995  1.393754  0.958482
2019-03-18 17:56:14.994758  2.498781 -0.472598 -1.205965 -1.312212
2019-03-19 17:56:14.994758 -0.347040 -0.249428 -2.204966 -1.742403
2019-03-20 17:56:14.994758  0.871982  1.085327 -0.359912  1.901698
2019-03-21 17:56:14.994758 -0.953773 -0.310954 -0.255489 -0.001839


In [82]:
data={'animals':['cat','rat','snake','pig','vulture'],
     'age':[21,22,16,18,25],
     'visits':[6,7,8,9,10],
     'priority':['yes','no','no','yes','yes']}
labels=[1,2,3,4,5]
df2=pd.DataFrame(data,index=labels)
df2


animals  age  visits priority
1      cat   21       6      yes
2      rat   22       7       no
3    snake   16       8       no
4      pig   18       9      yes
5  vulture   25      10      yes

In [66]:
df2.dtypes   #strings are objects in Pd

animals     object
age          int64
visits       int64
priority    object
dtype: object

In [67]:
df1.head(3)

A         B         C         D
2019-03-16 17:56:14.994758 -0.153244 -2.442910 -0.811786  0.502355
2019-03-17 17:56:14.994758 -0.120559  0.247995  1.393754  0.958482
2019-03-18 17:56:14.994758  2.498781 -0.472598 -1.205965 -1.312212

In [68]:
df1.tail(2)

A         B         C         D
2019-03-20 17:56:14.994758  0.871982  1.085327 -0.359912  1.901698
2019-03-21 17:56:14.994758 -0.953773 -0.310954 -0.255489 -0.001839

In [69]:
df2.index


Int64Index([1, 2, 3, 4, 5], dtype='int64')

In [71]:
df2.keys

<bound method NDFrame.keys of    animals  age  visits priority
1      cat   21       6      yes
2      rat   22       7       no
3    snake   23       8       no
4      pig   24       9      yes
5  vulture   25      10      yes>

In [72]:
df2.describe()  #for integer values only not string

age     visits
count   5.000000   5.000000
mean   23.000000   8.000000
std     1.581139   1.581139
min    21.000000   6.000000
25%    22.000000   7.000000
50%    23.000000   8.000000
75%    24.000000   9.000000
max    25.000000  10.000000

In [79]:
df2.sort_values(by='age')[2:4]

animals  age  visits priority
1     cat   21       6      yes
2     rat   22       7       no

In [74]:
df2


animals  age  visits priority
1      cat   21       6      yes
2      rat   22       7       no
3    snake   23       8       no
4      pig   24       9      yes
5  vulture   25      10      yes

In [75]:
df2


animals  age  visits priority
1      cat   21       6      yes
2      rat   22       7       no
3    snake   23       8       no
4      pig   24       9      yes
5  vulture   25      10      yes

In [78]:
df2

animals  age  visits priority
1      cat   21       6      yes
2      rat   22       7       no
3    snake   16       8       no
4      pig   18       9      yes
5  vulture   25      10      yes

In [83]:
df2.to_csv('animal.csv')  #To create and save as CSV

In [84]:
df=pd.read_csv('animal.csv')  #Read from created CSV
df.head(3)

Unnamed: 0 animals  age  visits priority
0           1     cat   21       6      yes
1           2     rat   22       7       no
2           3   snake   16       8       no

In [85]:
df2.to_excel('animal.xlsx',sheet_name='animalList')


In [87]:
df5=pd.read_excel('animal.xlsx',sheet_name='animalList')

In [93]:

X=lambda a,b,c : a+b+c
print(X(10,15,20))


45


<function <lambda> at 0x000000000F02AF28>
